services:
  - type: web
    name: reguardian
    env: python
    buildCommand: pip install -r requirements-minimal.txt && solc-select install 0.8.19 && solc-select use 0.8.19
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
